// service_simple_bank.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0--rc2
// source: service_simple_bank.proto

package pb

import (
	create_user "github.com/Kartik30R/simple_bank/pb/create_user"
	login_user "github.com/Kartik30R/simple_bank/pb/login_user"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_service_simple_bank_proto protoreflect.FileDescriptor

const file_service_simple_bank_proto_rawDesc = "" +
	"\n" +
	"\x19service_simple_bank.proto\x12\x02pb\x1a\x11create_user.proto\x1a\x10login_user.proto2\xb5\x01\n" +
	"\n" +
	"SimpleBank\x12U\n" +
	"\n" +
	"CreateUser\x12!.pb.create_user.CreateUserRequest\x1a\".pb.create_user.CreateUserResponse\"\x00\x12P\n" +
	"\tLoginUser\x12\x1f.pb.login_user.LoginUserRequest\x1a .pb.login_user.LoginUserResponse\"\x00B%Z#github.com/Kartik30R/simple_bank/pbb\x06proto3"

var file_service_simple_bank_proto_goTypes = []any{
	(*create_user.CreateUserRequest)(nil),  // 0: pb.create_user.CreateUserRequest
	(*login_user.LoginUserRequest)(nil),    // 1: pb.login_user.LoginUserRequest
	(*create_user.CreateUserResponse)(nil), // 2: pb.create_user.CreateUserResponse
	(*login_user.LoginUserResponse)(nil),   // 3: pb.login_user.LoginUserResponse
}
var file_service_simple_bank_proto_depIdxs = []int32{
	0, // 0: pb.SimpleBank.CreateUser:input_type -> pb.create_user.CreateUserRequest
	1, // 1: pb.SimpleBank.LoginUser:input_type -> pb.login_user.LoginUserRequest
	2, // 2: pb.SimpleBank.CreateUser:output_type -> pb.create_user.CreateUserResponse
	3, // 3: pb.SimpleBank.LoginUser:output_type -> pb.login_user.LoginUserResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_service_simple_bank_proto_init() }
func file_service_simple_bank_proto_init() {
	if File_service_simple_bank_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_service_simple_bank_proto_rawDesc), len(file_service_simple_bank_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_service_simple_bank_proto_goTypes,
		DependencyIndexes: file_service_simple_bank_proto_depIdxs,
	}.Build()
	File_service_simple_bank_proto = out.File
	file_service_simple_bank_proto_goTypes = nil
	file_service_simple_bank_proto_depIdxs = nil
}
